package CapaUsuario;

import CapaNegocio.Reporte;
import java.util.Calendar;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

public class InsumosUtilizados extends javax.swing.JPanel {
    //Variables usadas para guardar datos a mostrar en pantalla
    LinkedList<Object[]> datosTabla = new LinkedList<Object[]>();
    DefaultTableModel modeloTabla = new DefaultTableModel();
    Calendar fechaAct = Calendar.getInstance();

    public InsumosUtilizados() {
        initComponents();
        
        jdcInsumosUtil.setDate(new java.sql.Date(fechaAct.getTimeInMillis()));
        
        //Crea las columnas del JTable
        modeloTabla.addColumn("Insumo");
        modeloTabla.addColumn("Unidad");
        modeloTabla.addColumn("Cantidad");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jdcInsumosUtil = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtInsumosUtil = new javax.swing.JTable();
        btnVer = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 580));
        setMinimumSize(new java.awt.Dimension(800, 580));
        setPreferredSize(new java.awt.Dimension(800, 580));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Insumos Utilizados");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Fecha:");

        jtInsumosUtil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdInsumo", "Insumo", "Unidad", "Cantidad Utilizada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtInsumosUtil.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtInsumosUtil);

        btnVer.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnVer.setText("Ver");
        btnVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVer)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jdcInsumosUtil, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdcInsumosUtil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(btnVer)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseClicked
        cargarJTB();
    }//GEN-LAST:event_btnVerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcInsumosUtil;
    private javax.swing.JTable jtInsumosUtil;
    // End of variables declaration//GEN-END:variables
    //Limpia campos de ingreso de datos
    public void clear(){
        DefaultTableModel dtm = (DefaultTableModel) jtInsumosUtil.getModel();
        dtm.setRowCount(0);
        jtInsumosUtil.setModel(dtm);
        
        datosTabla.clear();
    }
    
    //Limpia toda la pantalla
    public void clear_T(){
        clear();
        
        jdcInsumosUtil.setCalendar(Calendar.getInstance());
    }
    
    //Carga JTable con datos
    public void cargarJTB(){
        clear();
        
        Reporte.insumosUtilizados(jdcInsumosUtil.getCalendar(), datosTabla);
        
        ManejoTablas.cargarTabla(datosTabla, modeloTabla);
        
        jtInsumosUtil.setModel(modeloTabla);
    }
    
    //Actualiza la pantalla
    public void actualizarPantalla(){
        cargarJTB();
        
        jdcInsumosUtil.setDate(new java.sql.Date(fechaAct.getTimeInMillis()));
    }
}
