package CapaUsuario;

import CapaNegocio.Insumo;
import CapaNegocio.Insumos;
import javax.swing.JOptionPane;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

public class ListaInsumos extends javax.swing.JPanel {
    //Variables usadas para guardar datos a mostrar en pantalla
    LinkedList<Object[]> datosTabla = new LinkedList<Object[]>();
    DefaultTableModel modeloTabla = new DefaultTableModel();

    public ListaInsumos() {
        initComponents();
        
        //Crea las columnas del JTable
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Descripción");
        modeloTabla.addColumn("Categoría");
        modeloTabla.addColumn("Costo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtInsumos = new javax.swing.JTable();
        btnAgregarInsumo = new javax.swing.JButton();
        btnEliminarInsumo = new javax.swing.JButton();
        btnModificarInsumo = new javax.swing.JButton();
        btnVerStock = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 580));
        setMinimumSize(new java.awt.Dimension(800, 580));
        setPreferredSize(new java.awt.Dimension(800, 580));

        jtInsumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripción", "Categoria", "Costo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtInsumos.setColumnSelectionAllowed(true);
        jtInsumos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtInsumos);
        jtInsumos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jtInsumos.getColumnModel().getColumnCount() > 0) {
            jtInsumos.getColumnModel().getColumn(0).setResizable(false);
            jtInsumos.getColumnModel().getColumn(1).setResizable(false);
            jtInsumos.getColumnModel().getColumn(2).setResizable(false);
            jtInsumos.getColumnModel().getColumn(3).setResizable(false);
        }

        btnAgregarInsumo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnAgregarInsumo.setText("Agregar Insumo");
        btnAgregarInsumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarInsumoMouseClicked(evt);
            }
        });

        btnEliminarInsumo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnEliminarInsumo.setText("Eliminar Insumo");
        btnEliminarInsumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarInsumoMouseClicked(evt);
            }
        });

        btnModificarInsumo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnModificarInsumo.setText("Modificar Insumo");
        btnModificarInsumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarInsumoMouseClicked(evt);
            }
        });

        btnVerStock.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnVerStock.setText("Ver Stock");
        btnVerStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerStockMouseClicked(evt);
            }
        });

        btnAtras.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregarInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModificarInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVerStock, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtras)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificarInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVerStock, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarInsumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarInsumoMouseClicked
        Inicio.limpiarTodo();
        Inicio.ins.actualizarPantalla();
        Inicio.mostrarVentana(Inicio.ins);
    }//GEN-LAST:event_btnAgregarInsumoMouseClicked

    private void btnVerStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerStockMouseClicked
        Inicio.limpiarTodo();
        Inicio.sto.actualizarPantalla();
        Inicio.mostrarVentana(Inicio.sto);
    }//GEN-LAST:event_btnVerStockMouseClicked

    private void btnModificarInsumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarInsumoMouseClicked
        //Utiliza el numero de row para verificar que haya un elemento seleccionado
        int row = jtInsumos.getSelectedRow();
        
        if(row == -1){
            Mensajes.msjError("No hay insumos cargados.");
        }else{
            Insumo insum = new Insumo();
            insum = Insumo.traerUnInsumo((Integer)jtInsumos.getValueAt(row, 0));
        
            Inicio.limpiarTodo();
            Inicio.ins.cargarInsumo(insum);
            Inicio.mostrarVentana(Inicio.ins);
        }        
    }//GEN-LAST:event_btnModificarInsumoMouseClicked

    private void btnEliminarInsumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarInsumoMouseClicked
        //Utiliza el numero de row para verificar que haya un elemento seleccionado
        int row = jtInsumos.getSelectedRow();
        
        if(row == -1){
            Mensajes.msjError("No hay insumos cargados.");
        }else{
            if(Mensajes.msjConfim("¿Esta seguro que desea eliminar el insumo?") == JOptionPane.YES_OPTION){
                Insumo.eliminarInsumo((Integer)jtInsumos.getValueAt(row, 0));
        
                cargarJTB();
            }
        }        
    }//GEN-LAST:event_btnEliminarInsumoMouseClicked

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        Inicio.limpiarTodo();
        Inicio.listProd.actualizarPantalla();
        Inicio.mostrarVentana(Inicio.listProd);
    }//GEN-LAST:event_btnAtrasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarInsumo;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEliminarInsumo;
    private javax.swing.JButton btnModificarInsumo;
    private javax.swing.JButton btnVerStock;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtInsumos;
    // End of variables declaration//GEN-END:variables
    //Carga JTable con datos
    public void cargarJTB(){
        clear_T();
        
        Insumos.cargarTablaInsumos(datosTabla);
        
        ManejoTablas.cargarTabla(datosTabla, modeloTabla);
        
        jtInsumos.setModel(modeloTabla);
    }
    
    //Limpia toda la pantalla
    public void clear_T(){
        DefaultTableModel dtm = (DefaultTableModel) jtInsumos.getModel();
        dtm.setRowCount(0);
        jtInsumos.setModel(dtm);
        
        datosTabla.clear();
    }
    
    //Actualiza la pantalla
    public void actualizarPantalla(){
        cargarJTB();
    }
}
